services:
  deepparse:
    image: ghcr.io/graal-research/deepparse:0.9.13
    command: uvicorn deepparse.app.app:app --host 0.0.0.0
    ports:
      - 8000:8000
    networks:
      - intranet
    volumes:
      - "./data/:/root/.cache/deepparse"

networks:
  intranet:
